"""empty message

Revision ID: 884f9e18906e
Revises: c16b172edab1
Create Date: 2023-02-11 17:37:09.171743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884f9e18906e'
down_revision = 'c16b172edab1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_request_id'), 'request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_id'), table_name='request')
    op.drop_column('request', 'id')
    # ### end Alembic commands ###
