"""empty message

Revision ID: ae63284a381d
Revises: b732eecc4501
Create Date: 2023-01-21 23:45:14.180408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae63284a381d'
down_revision = 'b732eecc4501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parent', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent', type_='unique')
    # ### end Alembic commands ###
