"""empty message

Revision ID: c16b172edab1
Revises: 28b2fe0bafc8
Create Date: 2023-02-11 12:19:40.179303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16b172edab1'
down_revision = '28b2fe0bafc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
