"""empty message

Revision ID: d55e2ec8b716
Revises: 28b2fe0bafc8
Create Date: 2023-02-21 01:06:51.060659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd55e2ec8b716'
down_revision = '28b2fe0bafc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('is_master_class', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_master_class')
    # ### end Alembic commands ###
